name: smart-openehr-server
services:

  keycloak-postgres:
    image: postgres:16.2
    command: -c ssl=off
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: keycloak
    volumes:
      - psqldata_keycloak-postgres:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 30s
      timeout: 30s
      retries: 3
    networks:
      smart-network:

  keycloak:
    image: quay.io/keycloak/keycloak:26.0.5
    command: "start-dev --import-realm"
#    command: "export --dir /opt/keycloak/data/import --users realm_file --realm smart"
    ports:
      - "7080:8080"
      - "8443:8443"
      - "9999:8080"
    environment:
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://keycloak-postgres:5432/keycloak
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: keycloak
      KC_DB_URL_DATABASE: keycloak
      KC_DB_URL_HOST: hip-kc-postgres
      KC_HOSTNAME_PORT: 7080
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_HTTP_RELATIVE_PATH: /auth
      PROXY_ADDRESS_FORWARDING: "true"
      KC_HTTP_PORT: 8080
    depends_on:
      keycloak-postgres:
        condition: service_healthy
    volumes:
      - ./keycloak:/opt/keycloak/data/import
    networks:
      smart-network:

  mock-server:
    image: mockserver/mockserver
    ports:
      - "1080:1080"
    environment:
      MOCKSERVER_INITIALIZATION_JSON_PATH: /config/initializer.json
    volumes:
      - ./mock:/config
    networks:
      smart-network:

volumes:
  psqldata_keycloak-postgres:

networks:
  smart-network: { }
